# Generated by Django 4.2.16 on 2024-09-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='user_answer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='submission',
            name='answers',
        ),
        migrations.AddField(
            model_name='submission',
            name='answers',
            field=models.ManyToManyField(to='submissions.answer'),
        ),
    ]
